services:

  postgres:
    image: postgres:17
    container_name: artisanos_postgres

    environment:
      POSTGRES_USER: artisan
      POSTGRES_PASSWORD: artisan
      POSTGRES_DB: artisanos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8
    container_name: artisanos_redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: