global:
  resolve_timeout: 5m
  smtp_smarthost: '${ALERTMANAGER_SMTP_HOST}:${ALERTMANAGER_SMTP_PORT}'
  smtp_from: '${ALERTMANAGER_SMTP_FROM}'
  smtp_auth_username: '${ALERTMANAGER_SMTP_USERNAME}'
  smtp_auth_password: '${ALERTMANAGER_SMTP_PASSWORD}'

route:
  receiver: default
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical

receivers:
  - name: default
    email_configs:
      - to: '${ALERTMANAGER_EMAIL_TO}'
        send_resolved: true
  - name: critical
    email_configs:
      - to: '${ALERTMANAGER_CRITICAL_EMAIL_TO}'
        send_resolved: true
