import type { Metadata } from 'next';
import Link from 'next/link';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Building2,
  Check,
  CircleHelp,
  FileText,
  Landmark,
  Mail,
  MapPin,
  PencilLine,
  ReceiptText,
  RefreshCw,
  Settings2,
  ShieldCheck,
  Sparkles,
  UsersRound,
} from 'lucide-react';
import styles from './entreprise.module.css';

export const metadata: Metadata = {
  title: 'Configurer son entreprise | Aide Workermate',
  description: 'Guide Workermate pour modifier les informations de son entreprise, les valeurs par défaut des documents, les relances, la TVA et les comptes bancaires.',
};

const sections = [
  { id: 'acces', number: '01', label: 'Trouver les réglages' },
  { id: 'identite', number: '02', label: 'Identité et adresse' },
  { id: 'documents', number: '03', label: 'Documents' },
  { id: 'suivi', number: '04', label: 'Relances et TVA' },
  { id: 'banque', number: '05', label: 'Compte bancaire' },
  { id: 'equipe', number: '06', label: 'Équipe et rôles' },
];

function Path({ items }: { items: string[] }) {
  return <ol className={styles.path} aria-label="Chemin dans Workermate">{items.map((item) => <li key={item}>{item}</li>)}</ol>;
}

function SectionTitle({ number, kicker, title, id }: { number: string; kicker: string; title: React.ReactNode; id: string }) {
  return <header className="grid gap-3 sm:grid-cols-[5rem_1fr] sm:items-end"><span className="font-mono text-5xl font-bold tracking-[-0.08em] text-blue-300/70" aria-hidden="true">{number}</span><div><p className={styles.eyebrow}>{kicker}</p><h2 id={id} className={`${styles.display} mt-2 text-[clamp(2rem,4vw,3.2rem)]`}>{title}</h2></div></header>;
}

function Tag({ children, tone = 'blue' }: { children: React.ReactNode; tone?: 'blue' | 'teal' | 'amber' }) {
  const classes = tone === 'teal' ? 'border-teal-200/70 bg-teal-100/60 text-teal-800' : tone === 'amber' ? 'border-amber-200/70 bg-amber-100/65 text-amber-800' : 'border-blue-200/70 bg-blue-100/65 text-blue-800';
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-bold ${classes}`}>{children}</span>;
}

export default function CompanyHelpPage() {
  return (
    <div className={styles.root}>
      <div className={styles.sky} aria-hidden="true" />
      <div className={styles.grain} aria-hidden="true" />
      <div className={styles.content}>
        <section className="px-4 pb-20 pt-8 sm:px-6 sm:pb-28 sm:pt-12">
          <div className="mx-auto max-w-[78rem]">
            <Link href="/aide" className={`${styles.btn} px-4 py-2.5`}><ArrowLeft className="h-4 w-4 text-blue-700" aria-hidden="true" /> Centre d’aide</Link>
            <div className="mt-10 grid gap-12 lg:grid-cols-[0.86fr_1.14fr] lg:items-center lg:gap-16">
              <div>
                <p className={styles.eyebrow}>Centre d’aide · Configuration</p>
                <h1 className={`${styles.display} mt-4 text-[clamp(2.75rem,6vw,5.3rem)]`}>Votre entreprise, <em>à votre image.</em></h1>
                <p className="mt-6 max-w-xl text-lg leading-8 text-[#264968]">Une seule fiche pour vos coordonnées, vos documents et vos habitudes de facturation. Voici où la trouver, quoi renseigner et ce que chaque réglage change.</p>
                <div className="mt-8 flex flex-wrap gap-3"><a href="#acces" className={`${styles.btn} px-4 py-3`}><Settings2 className="h-4 w-4 text-blue-700" aria-hidden="true" /> Voir le parcours <ArrowDown className="h-4 w-4" aria-hidden="true" /></a><Tag tone="teal"><ShieldCheck className="h-3.5 w-3.5" aria-hidden="true" /> Guide basé sur l’écran actuel</Tag></div>
              </div>

              <div className={`${styles.glass} rounded-[2rem] p-4 sm:p-6`}>
                <div className="relative z-[1]">
                  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className={styles.eyebrow}>Aperçu pédagogique · exemple</p><h2 className="mt-2 text-2xl font-black text-[#0d2c4b]">Atelier Martin</h2><p className="mt-1 text-sm text-[#59728d]">La fiche qui alimente les nouveaux documents</p></div><span className="grid h-14 w-14 place-items-center rounded-2xl border border-white/80 bg-white/35 text-blue-800 shadow-[4px_5px_13px_rgba(63,113,170,.2),inset_1px_1px_0_rgba(255,255,255,.9)]"><Building2 className="h-7 w-7" aria-hidden="true" /></span></div>
                  <div className="relative mt-7 grid gap-3 sm:grid-cols-2"><div className={`${styles.well} rounded-2xl p-4`}><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-blue-800"><MapPin className="h-3.5 w-3.5" aria-hidden="true" /> Adresse</div><p className="mt-2 text-sm font-bold text-[#0d2c4b]">12 rue des Tilleuls</p><p className="text-sm text-[#59728d]">44000 Nantes · FR</p></div><div className={`${styles.well} rounded-2xl p-4`}><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-blue-800"><ReceiptText className="h-3.5 w-3.5" aria-hidden="true" /> Document</div><p className="mt-2 text-sm font-bold text-[#0d2c4b]">EUR · échéance 30 jours</p><p className="text-sm text-[#59728d]">Mentions et notes par défaut</p></div></div>
                  <div className="mt-4 flex flex-wrap items-center gap-2"><Tag tone="teal"><Check className="h-3.5 w-3.5" aria-hidden="true" /> Identité</Tag><ArrowRight className="h-4 w-4 text-blue-400" aria-hidden="true" /><Tag><FileText className="h-3.5 w-3.5" aria-hidden="true" /> Devis</Tag><ArrowRight className="h-4 w-4 text-blue-400" aria-hidden="true" /><Tag tone="amber"><Banknote className="h-3.5 w-3.5" aria-hidden="true" /> Facture</Tag></div>
                  <p className="mt-5 text-xs leading-5 text-[#59728d]">Illustration fictive : elle montre les effets possibles des réglages, pas un contrôle interactif.</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="mx-auto grid max-w-[78rem] gap-12 px-4 pb-28 sm:px-6 lg:grid-cols-[12rem_minmax(0,1fr)] lg:gap-14">
          <aside className="lg:sticky lg:top-28 lg:self-start" aria-label="Sommaire de la page"><p className={styles.eyebrow}>Sur cette page</p><nav className="mt-4"><ol className="space-y-2">{sections.map((section) => <li key={section.id}><a href={`#${section.id}`} className="group flex items-center gap-3 rounded-xl px-2 py-2 text-sm font-bold text-[#59728d] transition hover:bg-white/40 hover:text-blue-800"><span className="font-mono text-xs text-blue-400 group-hover:text-blue-700">{section.number}</span>{section.label}</a></li>)}</ol></nav><div className={`${styles.glass} mt-8 rounded-2xl p-4 text-sm leading-6 text-[#59728d]`}><PencilLine className="h-5 w-5 text-blue-700" aria-hidden="true" /><p className="mt-2 font-bold text-[#0d2c4b]">À retenir</p><p className="mt-1">Les changements concernent les nouveaux documents.</p></div></aside>

          <main className="min-w-0 space-y-28 sm:space-y-36">
            <section id="acces" className="scroll-mt-36 lg:scroll-mt-28" aria-labelledby="acces-title"><SectionTitle number="01" kicker="Le point de départ" id="acces-title" title={<>Tout commence dans <em>Entreprise</em>.</>} /><div className="mt-8 grid gap-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><Path items={['Menu principal', 'Entreprise']} /><p className="mt-5 max-w-xl text-[#264968]">Ouvrez le menu latéral, puis choisissez <strong className="text-[#0d2c4b]">Entreprise</strong>. Vous arrivez sur la fiche de l’entreprise active, avec ses coordonnées, ses paramètres de facturation et la liste de ses membres.</p><div className="mt-6 flex items-start gap-3 text-sm text-[#59728d]"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-teal-700" aria-hidden="true" /><p>La consultation est disponible dans l’espace de l’entreprise active. La modification est protégée par les rôles <strong className="text-[#0d2c4b]">OWNER</strong> et <strong className="text-[#0d2c4b]">ADMIN</strong>.</p></div></div><div className={`${styles.glass} rounded-[1.75rem] p-5 sm:p-7`}><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#173e78] text-white shadow-[4px_5px_10px_rgba(46,87,139,.25)]"><Building2 className="h-5 w-5" aria-hidden="true" /></div><div><p className="text-xs font-black uppercase tracking-widest text-blue-800">Navigation réelle</p><p className="font-black text-[#0d2c4b]">Entreprise</p></div></div><div className="mt-5 rounded-2xl bg-white/45 p-4 shadow-[inset_3px_3px_8px_rgba(88,139,193,.16),inset_-3px_-3px_8px_rgba(255,255,255,.7)]"><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold text-[#0d2c4b]">Fiche entreprise</span><Tag tone="teal">Active</Tag></div><p className="mt-2 text-sm text-[#59728d]">Cliquez sur <strong>Modifier</strong> pour ouvrir le formulaire complet.</p></div><div className="mt-4 flex items-center justify-center gap-3 text-xs font-bold text-blue-800"><span className="h-px flex-1 bg-blue-300/60" /><ArrowDown className="h-4 w-4" aria-hidden="true" /><span className="h-px flex-1 bg-blue-300/60" /></div><p className="text-center text-sm font-semibold text-[#59728d]">Un formulaire · plusieurs familles de réglages</p></div></div></section>

            <section id="identite" className="scroll-mt-28" aria-labelledby="identite-title"><SectionTitle number="02" kicker="Informations administratives" id="identite-title" title={<>Donnez à Workermate <em>les bons repères.</em></>} /><p className="mt-6 max-w-2xl text-[#264968]">Dans <strong className="text-[#0d2c4b]">Modifier l’entreprise</strong>, le bloc <strong className="text-[#0d2c4b]">Profil de l’entreprise</strong> regroupe les informations qui décrivent votre activité et alimentent vos documents.</p><div className="mt-10 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><div className={`${styles.glass} rounded-[1.75rem] p-5 sm:p-7`}><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="text-xs font-black uppercase tracking-widest text-blue-800">Profil de l’entreprise</p><p className="mt-2 text-lg font-black text-[#0d2c4b]">Ce que vous pouvez renseigner</p></div>{[['Nom', 'Nom affiché de l’entreprise'], ['Email', 'Adresse de contact'], ['Téléphone', 'Numéro de contact'], ['SIRET', 'Identifiant de 14 chiffres'], ['TVA intracommunautaire', 'Ex. FRXX123456789'], ['Logo principal', 'Identifiant du fichier logo']].map(([label, value]) => <div key={label} className={`${styles.well} rounded-xl p-3`}><p className="text-xs font-black uppercase tracking-wide text-[#59728d]">{label}</p><p className="mt-1 text-sm font-bold text-[#0d2c4b]">{value}</p></div>)}</div><div className="mt-6 border-t border-white/60 pt-5"><div className="flex items-center gap-2 text-sm font-bold text-blue-800"><MapPin className="h-4 w-4" aria-hidden="true" /> Adresse de facturation</div><p className="mt-2 text-sm text-[#59728d]">Choisissez une adresse existante, créez une nouvelle adresse, ou désassociez l’adresse. La nouvelle adresse exige une rue, un code postal et une ville.</p></div></div><div className={`${styles.paper} rounded-[1.75rem] p-5 sm:p-7`}><p className={styles.eyebrow}>Effet concret</p><div className="mt-5 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-800"><FileText className="h-6 w-6" aria-hidden="true" /></span><div><p className="font-black text-[#0d2c4b]">Vos documents partent du même socle</p><p className="text-sm text-[#59728d]">Coordonnées et adresse sont reprises lorsque vous préparez un devis ou une facture.</p></div></div><div className="mt-7 rounded-xl border-l-2 border-blue-500 bg-blue-50/75 p-4 text-sm leading-6 text-[#264968]"><strong className="text-[#0d2c4b]">À savoir :</strong> le champ logo est un identifiant de fichier dans le formulaire actuel ; cette aide ne présente donc pas de téléversement qui n’existe pas à cet endroit.</div></div></div></section>

            <section id="documents" className="scroll-mt-28" aria-labelledby="documents-title"><SectionTitle number="03" kicker="Personnalisation des documents" id="documents-title" title={<>Le même geste, <em>votre manière.</em></>} /><p className="mt-6 max-w-2xl text-[#264968]">Le bloc <strong className="text-[#0d2c4b]">Facturation</strong> ne modifie pas un document déjà créé : il prépare les valeurs par défaut des prochains devis et factures.</p><div className={`${styles.glass} mt-10 rounded-[1.75rem] p-5 sm:p-8`}><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr]"><div><Tag><Sparkles className="h-3.5 w-3.5" aria-hidden="true" /> Valeurs par défaut</Tag><h3 className={`${styles.display} mt-4 text-3xl`}>Une petite bibliothèque de décisions.</h3><p className="mt-4 text-sm leading-6 text-[#59728d]">Saisissez une fois vos habitudes : elles deviennent le point de départ des nouveaux documents, tout en restant modifiables au moment de leur création.</p></div><div className="grid gap-3 sm:grid-cols-3">{[['Conditions de règlement', 'Ex. paiement à 30 jours'], ['Mentions légales', 'Texte par défaut'], ['Note de bas de document', 'Information complémentaire']].map(([label, value]) => <div key={label} className={`${styles.well} rounded-2xl p-4`}><FileText className="h-5 w-5 text-blue-700" aria-hidden="true" /><p className="mt-3 text-sm font-black text-[#0d2c4b]">{label}</p><p className="mt-1 text-xs leading-5 text-[#59728d]">{value}</p></div>)}</div></div><div className="mt-8 border-t border-white/65 pt-6"><div className="grid gap-4 md:grid-cols-[1fr_auto_1fr] md:items-center"><div className="rounded-2xl bg-white/42 p-4"><p className="text-xs font-black uppercase tracking-widest text-[#59728d]">Vous réglez</p><p className="mt-1 font-black text-[#0d2c4b]">Entreprise → Modifier → Facturation</p></div><ArrowRight className="hidden h-5 w-5 justify-self-center text-blue-500 md:block" aria-hidden="true" /><ArrowDown className="mx-auto h-5 w-5 text-blue-500 md:hidden" aria-hidden="true" /><div className="rounded-2xl bg-blue-50/65 p-4"><p className="text-xs font-black uppercase tracking-widest text-blue-800">Workermate réutilise</p><p className="mt-1 font-black text-[#0d2c4b]">Pour les nouveaux devis et factures</p></div></div></div></div></section>

            <section id="suivi" className="scroll-mt-28" aria-labelledby="suivi-title"><SectionTitle number="04" kicker="Encaissement et fiscalité" id="suivi-title" title={<>Régler le rythme, <em>pas la réalité.</em></>} /><div className="mt-8 grid gap-6 lg:grid-cols-2"><div className={`${styles.glass} rounded-[1.75rem] p-5 sm:p-7`}><div className="flex items-start justify-between gap-4"><div><Tag tone="teal"><RefreshCw className="h-3.5 w-3.5" aria-hidden="true" /> Relances email</Tag><h3 className="mt-4 text-2xl font-black text-[#0d2c4b]">Décidez quand rappeler.</h3></div><Mail className="h-8 w-8 text-teal-700" aria-hidden="true" /></div><p className="mt-4 text-sm leading-6 text-[#59728d]">Activez les relances automatiques pour les factures émises, échues et non réglées, puis configurez :</p><ul className="mt-5 space-y-3 text-sm text-[#264968]"><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-700" aria-hidden="true" />Délai de première relance après échéance</li><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-700" aria-hidden="true" />Délai entre deux relances</li><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-700" aria-hidden="true" />Nombre maximum de tentatives</li></ul><p className="mt-6 rounded-xl bg-teal-50/70 p-3 text-xs leading-5 text-teal-900">Le client doit avoir une adresse email et la facture doit remplir les conditions d’envoi.</p></div><div className={`${styles.glass} rounded-[1.75rem] p-5 sm:p-7`}><div className="flex items-start justify-between gap-4"><div><Tag tone="amber"><ReceiptText className="h-3.5 w-3.5" aria-hidden="true" /> TVA</Tag><h3 className="mt-4 text-2xl font-black text-[#0d2c4b]">Décrire votre régime.</h3></div><Landmark className="h-8 w-8 text-amber-700" aria-hidden="true" /></div><p className="mt-4 text-sm leading-6 text-[#59728d]">Choisissez votre régime de TVA : <strong className="text-[#0d2c4b]">Franchise en base</strong> ou <strong className="text-[#0d2c4b]">Assujetti à la TVA</strong>. Si vous êtes assujetti, choisissez une déclaration mensuelle ou trimestrielle.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className={`${styles.well} rounded-xl p-4`}><p className="text-xs font-black uppercase tracking-widest text-[#59728d]">Devise</p><p className="mt-1 font-black text-[#0d2c4b]">EUR par défaut</p><p className="mt-1 text-xs text-[#59728d]">USD, GBP, CHF, CAD et AUD sont aussi proposés.</p></div><div className={`${styles.well} rounded-xl p-4`}><p className="text-xs font-black uppercase tracking-widest text-[#59728d]">Application</p><p className="mt-1 font-black text-[#0d2c4b]">Nouveaux documents</p><p className="mt-1 text-xs text-[#59728d]">Les documents existants ne sont pas réécrits.</p></div></div></div></div></section>

            <section id="banque" className="scroll-mt-28" aria-labelledby="banque-title"><SectionTitle number="05" kicker="Compte bancaire" id="banque-title" title={<>Ajouter un compte, <em>choisir le bon défaut.</em></>} /><div className="mt-8 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><div className={`${styles.paper} rounded-[1.75rem] p-5 sm:p-7`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-100 text-blue-800"><Landmark className="h-5 w-5" aria-hidden="true" /></span><div><p className={styles.eyebrow}>Dans le formulaire Modifier</p><h3 className="mt-1 text-xl font-black text-[#0d2c4b]">Section « Comptes bancaires »</h3></div></div><p className="mt-5 text-sm leading-6 text-[#59728d]">Utilisez <strong className="text-[#0d2c4b]">Ajouter un compte bancaire</strong> pour enregistrer ses informations, puis cochez le compte principal lorsque vous voulez le sélectionner par défaut.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{['Nom du compte et banque', 'Titulaire, IBAN et BIC', 'Devise', 'Solde initial et date'].map((item) => <div key={item} className={`${styles.well} rounded-xl p-3 text-sm font-bold text-[#0d2c4b]`}><Check className="mr-2 inline h-4 w-4 text-blue-700" aria-hidden="true" />{item}</div>)}</div></div><div className={`${styles.glass} rounded-[1.75rem] p-5 sm:p-7`}><p className={styles.eyebrow}>Règle simple</p><div className="mt-5 flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#173e78] text-white"><Banknote className="h-6 w-6" aria-hidden="true" /></span><div><p className="font-black text-[#0d2c4b]">Un compte par défaut</p><p className="text-sm text-[#59728d]">Les autres comptes restent enregistrés et visibles.</p></div></div><p className="mt-6 text-sm leading-6 text-[#59728d]">Le choix du compte principal est contrôlé par l’entreprise active. Un compte archivé n’est plus proposé comme compte actif.</p></div></div></section>

            <section id="equipe" className="scroll-mt-28" aria-labelledby="equipe-title"><SectionTitle number="06" kicker="À ne pas confondre" id="equipe-title" title={<>L’identité de l’entreprise et <em>les rôles de l’équipe.</em></>} /><div className={`${styles.glass} mt-8 rounded-[1.75rem] p-5 sm:p-8`}><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><div className="flex items-center gap-3"><UsersRound className="h-7 w-7 text-blue-800" aria-hidden="true" /><h3 className="text-2xl font-black text-[#0d2c4b]">Membres de l’entreprise</h3></div><p className="mt-4 text-sm leading-6 text-[#59728d]">Cette section se trouve sur la même page que la fiche entreprise, mais elle répond à une autre question : qui peut agir dans l’espace ? Les rôles disponibles sont <strong className="text-[#0d2c4b]">Owner</strong>, <strong className="text-[#0d2c4b]">Admin</strong> et <strong className="text-[#0d2c4b]">Membre</strong>.</p><p className="mt-4 text-sm leading-6 text-[#59728d]">Un Owner peut gérer tous les rôles. Un Admin peut gérer les membres qui ne sont pas Owner. Le retrait d’un membre demande une confirmation.</p></div><div className="grid gap-3 sm:grid-cols-3">{[['Owner', 'Tous les rôles', 'bg-blue-100/70'], ['Admin', 'Membres et Admins', 'bg-teal-100/70'], ['Membre', 'Accès à l’espace', 'bg-amber-100/70']].map(([role, access, color]) => <div key={role} className={`rounded-2xl border border-white/70 ${color} p-4`}><p className="text-lg font-black text-[#0d2c4b]">{role}</p><p className="mt-1 text-xs leading-5 text-[#59728d]">{access}</p></div>)}</div></div></div><div className="mt-6 flex items-start gap-3 text-sm text-[#59728d]"><CircleHelp className="mt-1 h-5 w-5 shrink-0 text-blue-700" aria-hidden="true" /><p>Cette page explique les réglages ; elle ne remplace pas l’écran <strong className="text-[#0d2c4b]">Entreprise</strong>, où les changements sont réellement enregistrés.</p></div></section>

            <section id="fin" className={`${styles.glass} scroll-mt-28 rounded-[2rem] p-6 text-center sm:p-10`} aria-labelledby="fin-title"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-700 text-white shadow-[5px_6px_0_#15458f]"><Sparkles className="h-7 w-7" aria-hidden="true" /></span><h2 id="fin-title" className={`${styles.display} mt-5 text-3xl sm:text-4xl`}>Vous savez où agir.</h2><p className="mx-auto mt-3 max-w-xl text-[#59728d]">Ouvrez votre espace, allez dans <strong className="text-[#0d2c4b]">Entreprise</strong>, puis choisissez <strong className="text-[#0d2c4b]">Modifier</strong>. Les valeurs enregistrées serviront de base aux prochains documents.</p><Link href="/aide" className={`${styles.btn} mt-7 px-5 py-3`}><ArrowLeft className="h-4 w-4 text-blue-700" aria-hidden="true" /> Retour au centre d’aide</Link></section>
          </main>
        </div>
      </div>
    </div>
  );
}
