name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: artisan
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: node --version
      - run: npm --version
      - run: npm install
      # - run: npm run lint
      # - run: npm run test
      - run: npm run build